version: "3.7"
services:
  railsapp:
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: railsapp
      DB_PORT: 3306
      DB_HOST: db
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    image: 'railsapp:latest'
    ports:
      - 3000:3000
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: railsapp
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - 3307:3306
volumes:
   mysql_data:
    driver: local
